export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const AUTH_USER = 'AUTH_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_PRODUCTS_BY_ARRIVAL = 'GET_PRODUCTS_BY_ARRIVAL';
export const GET_PRODUCTS_BY_SELL = 'GET_PRODUCTS_BY_SELL';
export const GET_BRANDS = 'GET_BRANDS';
export const GET_WOODS = 'GET_WOODS';
export const GET_PORDUCTS_TO_SHOP = 'GET_PORDUCTS_TO_SHOP';
export const POST_PRODUCT = 'POST_PRODUCT'
export const POST_BRAND = 'POST_BRAND'; 
export const POST_WOOD = 'POST_WOOD';
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL'
export const CLEAR_PRODUCT_DETAIL = 'CLEAR_PRODUCT_DETAIL'
    